// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: doctor.proto

package doctorrb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDoctorRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	FullName       string                 `protobuf:"bytes,1,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,2,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDoctorRequest) Reset() {
	*x = CreateDoctorRequest{}
	mi := &file_doctor_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDoctorRequest) ProtoMessage() {}

func (x *CreateDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDoctorRequest.ProtoReflect.Descriptor instead.
func (*CreateDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDoctorRequest) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *CreateDoctorRequest) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *CreateDoctorRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type GetDoctorRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDoctorRequest) Reset() {
	*x = GetDoctorRequest{}
	mi := &file_doctor_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDoctorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDoctorRequest) ProtoMessage() {}

func (x *GetDoctorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDoctorRequest.ProtoReflect.Descriptor instead.
func (*GetDoctorRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{1}
}

func (x *GetDoctorRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListDoctorsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsRequest) Reset() {
	*x = ListDoctorsRequest{}
	mi := &file_doctor_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsRequest) ProtoMessage() {}

func (x *ListDoctorsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsRequest.ProtoReflect.Descriptor instead.
func (*ListDoctorsRequest) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{2}
}

type DoctorResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	FullName       string                 `protobuf:"bytes,2,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	Specialization string                 `protobuf:"bytes,3,opt,name=specialization,proto3" json:"specialization,omitempty"`
	Email          string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DoctorResponse) Reset() {
	*x = DoctorResponse{}
	mi := &file_doctor_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoctorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoctorResponse) ProtoMessage() {}

func (x *DoctorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoctorResponse.ProtoReflect.Descriptor instead.
func (*DoctorResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{3}
}

func (x *DoctorResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *DoctorResponse) GetFullName() string {
	if x != nil {
		return x.FullName
	}
	return ""
}

func (x *DoctorResponse) GetSpecialization() string {
	if x != nil {
		return x.Specialization
	}
	return ""
}

func (x *DoctorResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

type ListDoctorsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Doctors       []*DoctorResponse      `protobuf:"bytes,1,rep,name=doctors,proto3" json:"doctors,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDoctorsResponse) Reset() {
	*x = ListDoctorsResponse{}
	mi := &file_doctor_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDoctorsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDoctorsResponse) ProtoMessage() {}

func (x *ListDoctorsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_doctor_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDoctorsResponse.ProtoReflect.Descriptor instead.
func (*ListDoctorsResponse) Descriptor() ([]byte, []int) {
	return file_doctor_proto_rawDescGZIP(), []int{4}
}

func (x *ListDoctorsResponse) GetDoctors() []*DoctorResponse {
	if x != nil {
		return x.Doctors
	}
	return nil
}

var File_doctor_proto protoreflect.FileDescriptor

const file_doctor_proto_rawDesc = "" +
	"\n" +
	"\fdoctor.proto\x12\fpackage_name\"p\n" +
	"\x13CreateDoctorRequest\x12\x1b\n" +
	"\tfull_name\x18\x01 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x02 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\"\"\n" +
	"\x10GetDoctorRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12ListDoctorsRequest\"{\n" +
	"\x0eDoctorResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tfull_name\x18\x02 \x01(\tR\bfullName\x12&\n" +
	"\x0especialization\x18\x03 \x01(\tR\x0especialization\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\"M\n" +
	"\x13ListDoctorsResponse\x126\n" +
	"\adoctors\x18\x01 \x03(\v2\x1c.package_name.DoctorResponseR\adoctors2\xff\x01\n" +
	"\rDoctorService\x12O\n" +
	"\fCreateDoctor\x12!.package_name.CreateDoctorRequest\x1a\x1c.package_name.DoctorResponse\x12I\n" +
	"\tGetDoctor\x12\x1e.package_name.GetDoctorRequest\x1a\x1c.package_name.DoctorResponse\x12R\n" +
	"\vListDoctors\x12 .package_name.ListDoctorsRequest\x1a!.package_name.ListDoctorsResponseBDZBgithub.com/bgl96395/ADP2_ASSIGNMENT2/doctor-service/proto;doctorrbb\x06proto3"

var (
	file_doctor_proto_rawDescOnce sync.Once
	file_doctor_proto_rawDescData []byte
)

func file_doctor_proto_rawDescGZIP() []byte {
	file_doctor_proto_rawDescOnce.Do(func() {
		file_doctor_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_doctor_proto_rawDesc), len(file_doctor_proto_rawDesc)))
	})
	return file_doctor_proto_rawDescData
}

var file_doctor_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_doctor_proto_goTypes = []any{
	(*CreateDoctorRequest)(nil), // 0: package_name.CreateDoctorRequest
	(*GetDoctorRequest)(nil),    // 1: package_name.GetDoctorRequest
	(*ListDoctorsRequest)(nil),  // 2: package_name.ListDoctorsRequest
	(*DoctorResponse)(nil),      // 3: package_name.DoctorResponse
	(*ListDoctorsResponse)(nil), // 4: package_name.ListDoctorsResponse
}
var file_doctor_proto_depIdxs = []int32{
	3, // 0: package_name.ListDoctorsResponse.doctors:type_name -> package_name.DoctorResponse
	0, // 1: package_name.DoctorService.CreateDoctor:input_type -> package_name.CreateDoctorRequest
	1, // 2: package_name.DoctorService.GetDoctor:input_type -> package_name.GetDoctorRequest
	2, // 3: package_name.DoctorService.ListDoctors:input_type -> package_name.ListDoctorsRequest
	3, // 4: package_name.DoctorService.CreateDoctor:output_type -> package_name.DoctorResponse
	3, // 5: package_name.DoctorService.GetDoctor:output_type -> package_name.DoctorResponse
	4, // 6: package_name.DoctorService.ListDoctors:output_type -> package_name.ListDoctorsResponse
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_doctor_proto_init() }
func file_doctor_proto_init() {
	if File_doctor_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_doctor_proto_rawDesc), len(file_doctor_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_doctor_proto_goTypes,
		DependencyIndexes: file_doctor_proto_depIdxs,
		MessageInfos:      file_doctor_proto_msgTypes,
	}.Build()
	File_doctor_proto = out.File
	file_doctor_proto_goTypes = nil
	file_doctor_proto_depIdxs = nil
}
